server:
  port: 8081

spring:
  mvc:
    static-path-pattern: /static/**
  main:
    allow-circular-references: true
  servlet:
# 上传文件配置
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  #德鲁伊连接池
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/drive_school?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化大小
      initialSize: 5
      #最小值
      minIdle: 5
      #最大值
      maxActive: 20
#  #邮件配置
  mail:
    username: 574064600@qq.com
    password: gkdxsqmwaisubeib
    host: smtp.qq.com
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            required: true
#mybaits配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
#mybaits日志
logging:
  level:
    com.yuan.mapper: debug
#分页配置
pagehelper:
  helper-dialect: mysql
#图片存储路径
Location:
  realPath: 'E:\Yuan\Project\drive_school\images\'
  mapperPath: '/photo/'